feat: add uncollected fees to dashboard
SwaprDAO/swapr-info pull request #71
Opened 2022-05-17 19:08 UTC by guerrap

# Summary

Related to #43 

Add a data card to the dashboard for the uncollected fees across the different networks.

![image](https://user-images.githubusercontent.com/9011637/168891111-35ae2dd6-f0ad-4001-9810-6c40a06bbe53.png)

# How To Test

1.  Open the page `dashboard`
- [ ] Verify it contains the `Uncollected fees` data card

2022-05-18 19:56 UTC, 0xVenky commented
LGTM! 🚀  Good job @guerrap :)

@wixzi you want to review this ? :)

2022-05-18 21:16 UTC, wixzi commented on src/contexts/Dashboard.js
> +};
may be move getUncollectedFees above the hook.

2022-05-18 21:17 UTC, wixzi commented on src/contexts/Dashboard.js
> +          ...state.feesData,
```suggestion
      
```
Are you sure you need old data?. Anyway the new objects will override the old ones.

2022-05-19 07:26 UTC, wixzi commented
I have given you a patch in keybase. Please check

2022-05-19 07:27 UTC, wixzi requested changes
I have given you a patch in keybase. Please check

2022-05-19 08:15 UTC, wixzi approved these changes

2022-05-19 08:17 UTC, merged